name: lp-pedidos-feature-pipeline

on:
  push:
    branches:
      - 'feature/*'

jobs:
  quality-check:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Importante para que Sonar compare con la rama base

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # Agregamos cache para que sea más rápido tras la primera corrida

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Static Code Analysis (SonarQube)
        run: mvn verify sonar:sonar -Dsonar.projectKey=Xoaq_spring-boot-actuator-demo -Dsonar.organization=xoaq -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.qualitygate.wait=true

      - name: Maven Build & Unit Tests
        # Si el análisis de Sonar falla por el Quality Gate, este paso no se ejecutará
        #Actualizando  sonar token
        # dando permisos... desde sonarcloud project permissions..
        # actualizando token en secrets de  LP
        #Last Try
# PRUEBA CAMBIO DEMO
#prueba cambio demo 2
#prueba cambio demo 3
        run: mvn clean test -B -T 1C