name: lp-pedidos-feature-pipeline

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # Fix: Se agrega -T 1C para optimizar el tiempo de compilación usando 1 hilo por core
      - name: Maven Build & Unit Tests
        run: mvn clean test -B -T 1C